services:
  node:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    network_mode: host

  prod:
    build: .
    command: sh -c "yarn build && yarn serve"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    network_mode: host

  dev:
    build: .
    command: yarn dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    network_mode: host

volumes:
  node_modules:
